import type { Metadata } from 'next'
import { Prose, CONTACT_EMAIL } from '@/components/site'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description:
    'How Optimally handles your data. Short version: your scans stay on your device, and we never sell your data.',
}

export default function Privacy() {
  return (
    <Prose title="Privacy Policy" effective>
      <div className="tldr">
        Short version: Optimally keeps your scans, profile and lists{' '}
        <strong>on your device</strong>. There are no accounts, we don&rsquo;t
        sell your data, and there are no ads or advertising trackers.
      </div>

      <h2>Who we are</h2>
      <p>
        Optimally is an iOS app that scans food and personal-care products and shows
        an ingredient-based score. This policy explains exactly what data the app
        handles and where it goes. It applies to the Optimally iOS app and to this
        website.
      </p>
      <p>
        Optimally is operated by Nathaniel Fiskå, a sole trader based in Norway. For
        any privacy question, email{' '}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>

      <h2>No account, ever</h2>
      <p>
        Optimally does not have accounts. We never ask for your name, email address,
        phone number or date of birth, and there is nothing to sign in to.
      </p>

      <h2>Data stored on your device</h2>
      <p>
        Your profile answers, scan history, saved items and shopping list are
        stored <strong>locally on your device</strong> and are not uploaded to
        any Optimally server. You can erase all of it at any time in{' '}
        <strong>Settings &rarr; Reset everything</strong>, or by deleting the
        app.
      </p>

      <h2>Product lookups</h2>
      <p>
        When you scan a barcode or search for a product name, that barcode or
        search term is sent to{' '}
        <a href="https://world.openfoodfacts.org">Open Food Facts</a> — and, for
        personal-care items, Open Beauty Facts — to retrieve the product&rsquo;s
        details. These are free, open, community-built databases. The request
        contains the barcode or search term only; it carries no identifier for
        you or your device. See the{' '}
        <a href="https://world.openfoodfacts.org/privacy">
          Open Food Facts privacy policy
        </a>
        .
      </p>

      <h2>Other services the app contacts</h2>
      <div className="scroller">
        <table>
          <tbody>
            <tr>
              <th>Service</th>
              <th>What is sent</th>
              <th>Why</th>
            </tr>
            <tr>
              <td>
                <strong>Open Food Facts</strong> / Open Beauty Facts
              </td>
              <td>A barcode, or a product search term</td>
              <td>To look up the product&rsquo;s ingredients and details</td>
            </tr>
            <tr>
              <td>
                <strong>Optimally swap service</strong>
                <br />
                (our Cloudflare Worker)
              </td>
              <td>A barcode, and nothing else</td>
              <td>
                To generate suggested alternatives for that product. The service
                looks the product up itself, so no text you type and no personal
                data ever reaches it. Results are cached by barcode and are
                identical for every user.
              </td>
            </tr>
            <tr>
              <td>
                <strong>openFDA</strong> (U.S. Food &amp; Drug Administration)
              </td>
              <td>A brand name or product name</td>
              <td>
                To check whether that product or brand appears in the public U.S.
                food recall database
              </td>
            </tr>
            <tr>
              <td>
                <strong>Apple</strong>
              </td>
              <td>Your purchase, handled entirely by Apple</td>
              <td>To sell and manage Optimally subscriptions</td>
            </tr>
            <tr>
              <td>
                <strong>RevenueCat</strong>
              </td>
              <td>
                An anonymous subscription ID generated by RevenueCat, plus basic
                device and app information their SDK collects (including
                Apple&rsquo;s per-vendor device identifier)
              </td>
              <td>
                To tell the app whether your subscription is active. Not linked
                to your name or email.
              </td>
            </tr>
            <tr>
              <td>
                <strong>PostHog</strong> (EU region)
              </td>
              <td>Anonymous usage events — see below</td>
              <td>Product analytics</td>
            </tr>
          </tbody>
        </table>
      </div>
      <p>
        None of these requests include your name, email address, contacts,
        precise location, or your scan history.
      </p>

      <h2>Camera and photos</h2>
      <p>
        The camera is used only to read barcodes and product labels. When you
        scan a label as a photo, the image is processed{' '}
        <strong>on your device</strong> to read the text — the photo itself is
        never uploaded to us or to anyone else. Saving a share card to your
        Photos happens only when you tap to save it.
      </p>

      <h2>Analytics — specifically</h2>
      <p>
        Optimally sends a small number of anonymous usage events to{' '}
        <a href="https://posthog.com">PostHog</a>, hosted in the{' '}
        <strong>European Union</strong>, so we can see where people get stuck and
        improve the app.
      </p>
      <p>Each event is tagged with:</p>
      <ul>
        <li>
          A <strong>random identifier</strong> generated on your device the first
          time you open the app. It is not Apple&rsquo;s advertising identifier
          (IDFA), not the vendor identifier (IDFV), and it is not linked to any
          identity. Deleting and reinstalling the app generates a new one.
        </li>
        <li>
          The app version, your iOS version, and whether the device is a phone or
          a tablet. Never the exact device model.
        </li>
      </ul>
      <p>
        The events themselves cover: progress through onboarding and the answers
        you pick there, that a scan started, succeeded or failed and the score
        band it fell into, which sections of a verdict you opened, and whether
        the paywall was shown or a purchase was made.
      </p>
      <p>
        <strong>What is never sent:</strong> no barcodes, no product names, no
        photos, no scan history, no name or email, no advertising identifier, and
        no precise location.
      </p>
      <p>
        We do not track you across other apps or websites, and Optimally does not
        integrate any advertising SDK.
      </p>

      <h2>Subscriptions</h2>
      <p>
        Optimally is sold as a subscription through Apple&rsquo;s App Store. Apple
        processes your payment and manages your subscription —{' '}
        <strong>we never see your card or payment details</strong>. We use
        RevenueCat to tell the app whether your subscription is active;
        RevenueCat identifies your purchase with an anonymous ID, not with your
        name or email. Apple&rsquo;s handling of your data is governed by{' '}
        <a href="https://www.apple.com/legal/privacy/">
          Apple&rsquo;s privacy policy
        </a>
        , and RevenueCat&rsquo;s by{' '}
        <a href="https://www.revenuecat.com/privacy">RevenueCat&rsquo;s</a>.
      </p>

      <h2>What we don&rsquo;t do</h2>
      <ul>
        <li>We don&rsquo;t sell or rent your personal data to anyone, for any price.</li>
        <li>We don&rsquo;t show third-party ads or use advertising trackers.</li>
        <li>We don&rsquo;t require an account, name or email to use the app.</li>
        <li>
          We don&rsquo;t take money from food brands, and no brand can pay to
          change a score.
        </li>
      </ul>

      <h2>Your rights</h2>
      <p>
        Because Optimally has no accounts, we hold no file on you that could be looked
        up, exported or corrected — there is no name or email to search by.
        Everything personal to you lives on your device, and{' '}
        <strong>Settings &rarr; Reset everything</strong> erases it immediately
        and permanently.
      </p>
      <p>
        If you are in the EU, UK, or a U.S. state with a privacy law, and you
        want the anonymous analytics events from your device deleted, email{' '}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> and we will do
        it. We may need you to tell us roughly when you used the app, since there
        is no identifier tying those events to you.
      </p>

      <h2>Data retention</h2>
      <p>
        On-device data stays until you delete it. Anonymous analytics events are
        retained for up to 12 months and then deleted.
      </p>

      <h2>Children</h2>
      <p>
        Optimally is not directed at children under 13, and we do not knowingly
        collect data from them. If you believe a child has provided us data,
        email us and we will remove it.
      </p>

      <h2>Changes</h2>
      <p>
        If this policy changes, we&rsquo;ll update this page and the effective
        date at the top. Material changes will also be flagged in the app.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about privacy, or a request under a privacy law? Email{' '}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>. We aim to reply
        within a few days.
      </p>

      <div className="note">
        Optimally&rsquo;s scores are an information tool, not medical advice, and not
        a substitute for guidance from a qualified professional.
      </div>
    </Prose>
  )
}
